const ROOT_URL = 'http://lovelaiguanjia.com';
// const ROOT_URL = 'http://cio.ueepub.cn';

export const API_URL = {
  CITYLIST: {
    domain: ROOT_URL,
    apiUrl: '/Admin/system/cityList',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/system/cityList',
    remark: '大区列表',
    method: 'POST',
    writer: '王健男',
  },
  CITYADD: {
    domain: ROOT_URL,
    apiUrl: '/Admin/system/cityAdd',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/system/cityAdd',
    remark: '添加大区',
    method: 'POST',
    writer: '王健男',
  },
  CITYDELETE: {
    domain: ROOT_URL,
    apiUrl: '/Admin/system/cityDelete',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/system/cityDelete',
    remark: '删除大区',
    method: 'POST',
    writer: '王健男',
  },
  CITYEIDT: {
    domain: ROOT_URL,
    apiUrl: '/Admin/system/cityEidt',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/system/cityEidt',
    remark: '编辑大区信息展示',
    method: 'POST',
    writer: '王健男',
  },
  CITYDOEIDT: {
    domain: ROOT_URL,
    apiUrl: '/Admin/system/cityDoEidt',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/system/cityDoEidt',
    remark: '修改大区',
    method: 'POST',
    writer: '王健男',
  },
  BRANCHMANAGER: {
    domain: ROOT_URL,
    apiUrl: '/Admin/admin/branchManager',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/admin/branchManager',
    remark: '添加大区经理',
    method: 'POST',
    writer: '王健男',
  },
  BRANCHMANAGERLIST: {
    domain: ROOT_URL,
    apiUrl: '/Admin/admin/branchManagerList',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/admin/branchManagerList',
    remark: '大区经理列表',
    method: 'POST',
    writer: '王健男',
  },
  BRANCHMANAGEREDIT: {
    domain: ROOT_URL,
    apiUrl: '/Admin/admin/branchManagerEdit',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/admin/branchManagerEdit',
    remark: '显示大区经理信息',
    method: 'POST',
    writer: '王健男',
  },
  BRANCHMANAGERDOEDIT: {
    domain: ROOT_URL,
    apiUrl: '/Admin/admin/branchManagerDoEdit',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/admin/branchManagerDoEdit',
    remark: '修改大区经理信息',
    method: 'POST',
    writer: '王健男',
  },
  BRANCHMANAGERDELETE: {
    domain: ROOT_URL,
    apiUrl: '/Admin/admin/branchManagerDelete',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/admin/branchManagerDelete',
    remark: '删除大区经理',
    method: 'POST',
    writer: '王健男',
  },
  CUSTOMERSERVICELIST: {
    domain: ROOT_URL,
    apiUrl: '/Admin/admin/customerServiceList',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/admin/customerServiceList',
    remark: '客服列表',
    method: 'POST',
    writer: '王健男',
  },
  CUSTOMERSERVICEEDIT: {
    domain: ROOT_URL,
    apiUrl: '/Admin/admin/customerServiceEdit',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/admin/customerServiceEdit',
    remark: '显示客服信息',
    method: 'POST',
    writer: '王健男',
  },
  CUSTOMERSERVICEDOEDIT: {
    domain: ROOT_URL,
    apiUrl: '/Admin/admin/customerServiceDoEdit',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/admin/customerServiceDoEdit',
    remark: '修改客服信息',
    method: 'POST',
    writer: '王健男',
  },
  CUSTOMERSERVICEADD: {
    domain: ROOT_URL,
    apiUrl: '/Admin/admin/customerServiceAdd',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/admin/customerServiceAdd',
    remark: '添加客服',
    method: 'POST',
    writer: '王健男',
  },
  CUSTOMERSERVICEDELETE: {
    domain: ROOT_URL,
    apiUrl: '/Admin/admin/customerServiceDelete',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/admin/customerServiceDelete',
    remark: '删除客服',
    method: 'POST',
    writer: '王健男',
  },
  AREAMANAGERLIST: {
    domain: ROOT_URL,
    apiUrl: '/Admin/staff/areaManagerList',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/staff/areaManagerList',
    remark: '区域经理列表',
    method: 'POST',
    writer: '王健男',
  },
  AREAMANAGERADD: {
    domain: ROOT_URL,
    apiUrl: '/Admin/staff/areaManagerAdd',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/staff/areaManagerAdd',
    remark: '添加区域经理',
    method: 'POST',
    writer: '王健男',
  },
  LEADERLIST: {
    domain: ROOT_URL,
    apiUrl: '/Admin/staff/leaderList',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/staff/leaderList',
    remark: '大区经理/区域经理',
    method: 'POST',
    writer: '王健男',
  },
  AREAMANAGEREDIT: {
    domain: ROOT_URL,
    apiUrl: '/admin/staff/areaManagerEdit',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/admin/staff/areaManagerEdit',
    remark: '显示区域经理信息',
    method: 'POST',
    writer: '王健男',
  },
  AREAMANAGERDOEDIT: {
    domain: ROOT_URL,
    apiUrl: '/Admin/staff/areaManagerDoEdit',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/staff/areaManagerDoEdit',
    remark: '修改区域经理',
    method: 'POST',
    writer: '王健男',
  },
  AREAMANAGERDELETE: {
    domain: ROOT_URL,
    apiUrl: '/Admin/staff/areaManagerDelete',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/staff/areaManagerDelete',
    remark: '删除区域经理',
    method: 'POST',
    writer: '王健男',
  },
  EMPLOYEELIST: {
    domain: ROOT_URL,
    apiUrl: '/Admin/staff/employeeList',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/staff/employeeList',
    remark: '员工列表',
    method: 'POST',
    writer: '王健男',
  },
  EMPLOYEEEDIT: {
    domain: ROOT_URL,
    apiUrl: '/Admin/staff/employeeEdit',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/staff/employeeEdit',
    remark: '显示员工修改信息',
    method: 'POST',
    writer: '王健男',
  },
  EMPLOYEEADDEDIT: {
    domain: ROOT_URL,
    apiUrl: '/Admin/staff/employeeAddEdit',
    author: '赵斌',
    fetchUrl: ROOT_URL + '/Admin/staff/employeeAddEdit',
    remark: '员工添加/修改',
    method: 'POST',
    writer: '王健男',
  },
}
